### ISSUE TITLE
conflict with yast2-ruby-bindings

### ISSUE THREAD

**Issue by mvidner** [yast/ycp-killer#1]
It works! I have tried on "nfs-client nf-server testsuite" and got OK: 21, ERROR(y2r): 18.

But on the 1st try there were more failures, including segfaults (BTW Ruby segfaults are beautiful, check them out!) It turns out that having `yast2-ruby-bindings` installed makes yast-core want to use the newly created NfsServer.rb, boom!

I remember we compiled yast-core with a nonsense prefix to work around this. I worked around it by `zypper rm yast2-ruby-bindings`.

**Comment by jreidinger** [comment]
Actually it should not conflict, otherwise it makes it impossible to convert third party software. Solution for me is to require proper version of ruby-bindings that works with newly translated module. ( I plan to fix build in obs next week )

**Comment by dmajda** [comment]
This won't be a problem once we separate directories where the YaST module source is stored and where the translated one is built. All the module/include paths used by `ycpc` and `y2r` will point to the source directory, but the `*.rb` files will be built in a different one, so they won't be loaded.

Keeping this issue open until this is actually implemented.

**Comment by jreidinger** [comment]
issue is solved by pull request #2

**Comment by mvidner** [comment]
Not a problem since we've separated the working and resulting directories.
