### ISSUE TITLE
Installer gets aborted in installation proposal (first stage)

### ISSUE THREAD

**Issue by kobliha** [yast/ycp-killer#407]
Steps to reproduce:
- New installation
- Do not use automatic configuration
- Use add-ons (maybe not relevant)
- In addons use community repos and let them fail
- Use own partitioning 1 GB swap and the rest for /
- Create own first user (no auto-login, root pass not the same)
- Set root password
- It will fail somewhere in the installation proposal with
  
  modules/ProductControl.rb:900 Calling `inst_proposal ($["enable_back":true, "enable_next":true, "proposal":"initial"]) returned `abort

Some other logs:

```
ProductControl.rb:643 Stage: initial Mode: installation, Type: initial
ProductControl.rb:675 Proposal modules: nil
inst_proposal.rb:647 getting proposals for stage: "initial" mode: "installation" proposal type: "initial"
ProductControl.rb:643 Stage: initial Mode: installation, Type: initial
ProductControl.rb:675 Proposal modules: nil
inst_proposal.rb:650 No proposals available
```

with several

```
ycp/ops.rb:37 Index 0 is out of array size
```

between these calls

I'll try to minimize the test case.

Full logs are available at http://bestie.suse.cz/ycp-killer/issue_407/

**Comment by kobliha** [comment]
OK, minimized: Probably caused by the add-ons incorporated into the workflow (by default they are disabled)
Linuxrc: insecure=1 netsetup=dhcp
- New installation
- Use add-ons, choose Community repos and let them fail
- Time zone
- Minimal X
- Let partitioner do what it wants to do
- Skip first user
- Skip root password
- Then it fails in proposal

Wild guess: Add-ons allow to add their own workflow or modify the current one. As no add-on is actually added, workflow merge can fail and thus "No proposals available".

**Comment by lslezak** [comment]
@kobliha can you reproduce it with original 13.1 M1? (http://download.opensuse.org/distribution/13.1-Milestone1/iso/)

**Comment by vmoravec** [comment]
Today I re-tested this scenario twice with varying options and both attempts were successful without any error or problem.
