### ISSUE TITLE
yast2-fingerprint-reader does  not react on Finish button

### ISSUE THREAD

**Issue by jsuchome** [yast/ycp-killer#416]
Running yast2 fingerprint-reader, I can see the dialog with enable/disable options, but there's no reaction from UI when I press Finish.

Note: I do not actually have device supported, I commented line 53 in FingerprintReader.rb to get pass the warning.

**Comment by jsuchome** [comment]
Here's the reason, I think: there's empty block in original dialogs.ycp, which is not correctly converted:
https://github.com/yast/yast-fingerprint-reader/blob/master/src/dialogs.ycp#L138

The "next" block is inside the "users" block after the conversion.

**Comment by jreidinger** [comment]
@dmajda works on issue

**Comment by dmajda** [comment]
The bug was in Y2R and I [fixed it](https://github.com/yast/y2r/commit/dc026b4812e88699e46a06712e9f6b379a9345d4). I submitted packages compiled with fixed Y2R into YaST:Head:ruby.
