### ISSUE TITLE
Files with ".in" suffix missing in generated package

### ISSUE THREAD

**Issue by vmoravec** [yast/ycp-killer#435]
due to the workflow in generating/executing makefiles.
- found in `yast2` package
- missing file `library/network/src/scrconf/network.scr.in` or
  
  `````` library/general/src/module/Version.ycp.in```
  
  This bug blocks e.g. network configuration, y2log shows:
  ``` NetworkInterfaces: Couldn't find an agent to handle '.network.value."eth0".BOOTPROTO' 
  SCR::Write() failed ```
  ``````

**Comment by lslezak** [comment]
Fixed by #438.
