### ISSUE TITLE
yast leaves mess in /tmp

### ISSUE THREAD

**Issue by jirislaby** [yast/ycp-killer#437]
ls /tmp/YaST2-*
/tmp/YaST2-08281-OYhLev:
exit  stderr  stdout

/tmp/YaST2-17893-jd5R29:
exit  stderr  stdout

/tmp/YaST2-17933-JiQkn3:
exit  stderr  stdout

/tmp/YaST2-18091-qpTggc:

/tmp/YaST2-18091-zUVVYp:
exit  stderr  stdout

/tmp/YaST2-18130-1cROal:
exit  stderr  stdout

/tmp/YaST2-18170-UY3whw:
exit  stderr  stdout

/tmp/YaST2-18224-R6vm9d:
exit  stderr  stdout

/tmp/YaST2-18242-AccmYW:
exit  stderr  stdout

/tmp/YaST2-18264-RpaaX5:
exit  stderr  stdout

/tmp/YaST2-18382-vAJ5ZU:
exit  stderr  stdout

/tmp/YaST2-18382-3iIE7c:

/tmp/YaST2-18486-E99LMl:

/tmp/YaST2-18534-H1CdcY:
exit  stderr  stdout

/tmp/YaST2-18570-9zo9I0:
exit  stderr  stdout  xkbctrl.out

/tmp/YaST2-18632-UYyeyw:
exit  stderr  stdout  sysconfig-agent.scr  sysconfig-template-agent.scr  treedef.ycp

/tmp/YaST2-18666-THWQG0:
exit  stderr  stdout  targetMap_i  targetMap_ii  targetMap_s_initial_0

/tmp/YaST2-18803-kAaFjN:

/tmp/YaST2-18803-T2cvvw:
exit  stderr  stdout  targetMap_i  targetMap_ii  targetMap_s_initial_0

/tmp/YaST2-18965-u734Lo:
exit  stderr  stdout

/tmp/YaST2-19013-IvXVqR:
exit  stderr  stdout

/tmp/YaST2-19077-Mb4sCS:

/tmp/YaST2-20427-iDhira:
exit  stderr  stdout

/tmp/YaST2-22106-59RYcC:
exit  stderr  stdout

**Comment by jreidinger** [comment]
looks like related to different way when object are destroyed. I will investigate it. Related part is probably SystemAgent

**Comment by jreidinger** [comment]
@jirislaby One question. This often happen if yast crash, do you see anything unusual? Also when such mess appear? immediatelly after installation? Some steps to reproduce it will be great.

**Comment by jsuchome** [comment]
I tried running yast2-security. The module correctly exited (at least nothing indicating the crash), but tmp directory was indeed not deleted. It contains only empty files 'stderr', 'stdout' and 'exit' which just '0' as content

**Comment by vmoravec** [comment]
This issue affects all yast modules (ncurses ui) I have tried so far, it is obviously not dependend on the exit status nor on any specific module parts. Even if I only start and quit the module without any action, the temp dirs get created and remain intact after yast exits.

**Comment by jreidinger** [comment]
finally after detecting few annoying memory leaks I found root of issue and fix it.
Thanks for report. Fix should be in build tomorrows build.
