### ISSUE TITLE
Builtin index called on wrong type String

### ISSUE THREAD

**Issue by jsuchome** [yast/ycp-killer#458]
Calling yast2 image-creator produces some warnings in y2log, see http://pastebin.suse.de/7095

**Comment by jsuchome** [comment]
Tested with openSUSE-Factory-RUBY-YAST-fullDVD-x86_64-Build0001-Media.iso

**Comment by jsuchome** [comment]
The original @KiwiConfig map is altered at line 3849. Well, maybe earlier, there's same operation at line 3841, but 3849 handles "packages" submap which results in error above.

**Comment by jreidinger** [comment]
Problem is that global variable have accessors so y2r doesn't use deep copy, but accessor also doesn't do deep copy. Fix will be needed in global variable accessor.

**Comment by jreidinger** [comment]
fixed in https://github.com/yast/yast-ruby-bindings/commit/daaa7cfb22db02508505b16e092e3ec9fd7a3149 . Will be release probably today

**Comment by jreidinger** [comment]
relased as ruby-bindings 1.1.0 . Please reopen if issue still exists

**Comment by jreidinger** [comment]
Reopen as fix breaks different use case and proper fix need to be in y2r - https://github.com/yast/y2r/issues/25

**Comment by dmajda** [comment]
This should be fixed by fixing yast/y2r#25. I already submitted fixed packages.

@jsuchome Could you please verify that this is really fixed and close the issue if so? Thanks.

**Comment by jsuchome** [comment]
Yes, this problem seems to be gone.
