### ISSUE TITLE
Undefined method for YCP::HttpServerWidgetsClass

### ISSUE THREAD

**Issue by vmoravec** [yast/ycp-killer#462]
The exception comes from yast2 module `http-server` during the initialization from the file `/usr/share/YaST2/modules/HttpServerWidgets.rb`

`NameError: undefined method `initFwOpen' for class `YCP::HttpServerWidgetsClass'`

**Comment by jreidinger** [comment]
upstream issue - https://github.com/yast/yast-http-server/issues/1

**Comment by vmoravec** [comment]
Tested the package version 2.24.1-1.1 and it's been fixed successfuly;
