### ISSUE TITLE
Version.ycp not translated to rb

### ISSUE THREAD

**Issue by jsuchome** [yast/ycp-killer#466]
Part of yast2 package is Version.ycp file, even after conversion to ruby

**Comment by lslezak** [comment]
The YCP killer looks for `*.ycp` and `*.yh` files. The problem is that `Version.ycp` is generated from `Version.ycp.in` file which is ignored during conversion.

The fix should be trivial.

**Comment by lslezak** [comment]
Fixed in #555.
