### ISSUE TITLE
Something is likely wrong with yast2.patch

### ISSUE THREAD

**Issue by dmajda** [yast/ycp-killer#468]
The following sequence of commands leads to an error:

```
$ ./yk clone yast2
$ ./yk restructure yast2
$ ./yk patch yast2
$ ./yk reset yast2
$ ./yk restructure yast2
$ ./yk patch yast2
```

The error:

```
[1/1] Processing yast2:
  * Patching...
    ERROR: Patching failed.

Command git failed:
error: library/general/Makefile.am: already exists in working directory
```

I guess something is wrong with the yast2 patch.

@lslezak Could you have a look?

**Comment by jreidinger** [comment]
@dmajda I also face this problem. Problem is that git reset do not remove generated file.

**Comment by lslezak** [comment]
This file is **added** and as Pepa mentioned it's not removed by `git reset` as it is not tracked by Git.

Probably the only solution is to remove all untracked files in `yk reset`...

**Comment by lslezak** [comment]
Fixed in https://github.com/yast/ycp-killer/pull/470
