### ISSUE TITLE
Error in y2log: SetFunctionsKeys called with wrong type

### ISSUE THREAD

**Issue by gabi2** [yast/ycp-killer#556]
Milestone 3 ncurses installation:
Just after initialization of ncurses there is an error message in y2log (see below). Nevertheless the function keys work correctly/are usable. 

[ncurses] NCurses.cc(init):326 NCurses ready
[ui] YSettings.cc(setProgDir):60 Set progDir to "/usr/share/YaST2"
[ui] YSettings.cc(setProgDir):61 progDir is now locked.
[ui] YUINamespace.cc(no_match):812 Function SetFunctionKeys called with wrong type <unspec> (map)
[ui] YUINamespace.cc(no_match):813 TODO: display the candidates
[ui] YPushButton.cc(setFunctionKey):188 Guessing button role YHelpButton for YPushButton "Help" at 0x7ff694006c30 from function key F1

**Comment by jreidinger** [comment]
Problem is that  SetFunctionKeys want as parameter `map<string,integer>` but gues only type map without specification. I need to check ycp-ui-bindings to check how it is supposed to work.

**Comment by jreidinger** [comment]
@tgoettlicher it looks like problem in ycp-ui-bindings.
ycp-ui-bindings use for overloaded function method vt2type 
https://github.com/yast/yast-ycp-ui-bindings/blob/master/src/YUINamespace.cc#L839
but this method return only generic unspecifed map, so it can never match
https://github.com/yast/yast-core/blob/master/libycp/src/TypeStatics.cc#L45

Solution can be to not specify maps and lists in ( return value is OK, as if you want map<any> and get map<integer,string> it matches )
https://github.com/yast/yast-ycp-ui-bindings/blob/master/src/YUINamespace.h#L298
For SetFunctionKeys it is already solved:
https://github.com/yast/yast-ycp-ui-bindings/blob/master/src/YCP_UI.cc#L1507

so it can be easy modification of signature. Do you agree Thomas?

**Comment by jreidinger** [comment]
pull request created https://github.com/yast/yast-ycp-ui-bindings/pull/8/files

**Comment by tgoettlicher** [comment]
Go ahead. :airplane:

**Comment by jreidinger** [comment]
thanks merged.
