### ISSUE TITLE
autoyast not working with openSUSE-Factory-RUBY-YAST-fullDVD-x86_64-Milestone3-Build0001-Media

### ISSUE THREAD

**Issue by thomas-fehr** [yast/ycp-killer#557]
This is reported as bnc#829673 and currently assigned to me.
Since I am currently fixing another autoyast bug in 13.1M3 and
do not see any crash, I am quite sure this is related to Ruby 
conversion and not autoyast itself. 

Would be great if someone could have a look.

**Comment by jsuchome** [comment]
Hm, maybe it is not even autYaST based installation...

**Comment by thomas-fehr** [comment]
Could not reproduce
