### ISSUE TITLE
Second part of text mode installation: disturbing console messages

### ISSUE THREAD

**Issue by gabi2** [yast/ycp-killer#558]
Milestone 3 ncurses installation:
In second part of installation console messages appear on the screen, see attached images. 
Not seen during YCP installation.
![ruby_inst_m3](https://f.cloud.github.com/assets/1658828/804143/2c939c94-ee05-11e2-9648-28efeedb8271.png)
![ruby_inst_m3_completed](https://f.cloud.github.com/assets/1658828/804144/37992618-ee05-11e2-9a7c-fa5282193acb.png)

**Comment by jsuchome** [comment]
This does not seem ruby related, is it diferent with M3 installation?

**Comment by dmajda** [comment]
I've seen similar disturbances in the past and they were casued by systemd, so that would be my hunch here.

**Comment by dmajda** [comment]
@jsuchome Did you see this problem in any of your installation trials? If not, I'd close this issue as it's very likely unrelated to the Ruby translation.

**Comment by vmoravec** [comment]
I have seen such issue only when bootloader startup had been failing (already fixed), but haven't seen this during normal installation workflow. Today I tried to reproduce this with the latest image but without success. Recommend to close this and eventually reopen later if needed.

**Comment by dmajda** [comment]
OK, closing.
