### ISSUE TITLE
Can't start several config modules from 'Network Configuration' overview

### ISSUE THREAD

**Issue by gabi2** [yast/ycp-killer#562]
Milestone 3 installation, don't use automatic configuration.

Couldn't start 'ISDN', 'DSL' and 'Modem' configuration from 'Network Configuration' overview.
Similar logging about "Invalid cast of YCP value '.propose'!"  in y2log:

 2013-07-17 04:43:37 &lt;1&gt; linux(1965) [Interpreter] clients/isdn_proposal.rb:88 Calling YaST client isdn
2013-07-17 04:43:37 &lt;1&gt; linux(1965) [Ruby] yast/wfm.rb:79 Call client /usr/share/YaST2/clients/isdn.rb
2013-07-17 04:43:37 &lt;1&gt; linux(1965) [Ruby] clients/isdn.rb:58 ----------------------------------------
2013-07-17 04:43:37 &lt;1&gt; linux(1965) [Ruby] clients/isdn.rb:59 ISDN module started
2013-07-17 04:43:37 &lt;3&gt; linux(1965) [Interpreter] clients/isdn.rb:69 Invalid cast of YCP value '.propose'! Should be but is not String!

**Comment by jsuchome** [comment]
I can confirm this, calling ISDN from network proposal ends with the crash. Calling 'yast2 isdn' standalone works.

**Comment by jsuchome** [comment]
BTW, to simulate network proposal on running system, call 'yast2 test_proposal network'

**Comment by mchf** [comment]
note: I've checked it for ycp version and it didn't crashed.

**Comment by dmajda** [comment]
@jsuchome Could you try to investigate why is the invalid value passed there?

**Comment by jsuchome** [comment]
isdn_proposal.rb calls isdn this way (line 85):

```
@seq = WFM.CallFunction("isdn", [path(".propose")])
```

And isdn.rb crashes with the above error.
If I get rid of the paths here, so I change mentioned line to 

```
@seq = WFM.CallFunction("isdn", [".propose"])
```

and adapt the checking line 71 in isdn.rb to

```
if (WFM.Args(0) == ".propose")
```

It works.

**Comment by jsuchome** [comment]
The crash actually happens on the line with reading args (line 69 of isdn.rb), when one arg is a path:

```
  @args = WFM.Args
```

**Comment by jsuchome** [comment]
Yes, passing paths as arguments to WFM.CallFunction is broken, e.g. TV proposal behaves the same way

**Comment by dmajda** [comment]
Thanks for the investigation. I looked really quickly though the relevant code path in Ruby bidnings, but I didn't find anything suspicious, so I guess I'll leave this one to @jreidinger.

**Comment by jreidinger** [comment]
fix is in https://github.com/yast/yast-ruby-bindings/pull/69

**Comment by jreidinger** [comment]
fix merged
