### ISSUE TITLE
'General Network Settings' not usable when started from 'Network Configuration' overview

### ISSUE THREAD

**Issue by gabi2** [yast/ycp-killer#564]
Milestone 3, don't use automatic configuration.
'Network Setup Method' is displayed incomplete when started from 'Network Configuration' overview.
y2log:
&lt;1&gt; linux(1966) [ncurses] NCPopupMenu.cc(postAgain):115 Menu item: General &Network Settings...
&lt;1&gt; linux(1966) [Ruby] clients/inst_proposal.rb:167 Proposal - UserInput: 'networkmode'
&lt;1&gt; linux(1966) [Interpreter] clients/inst_proposal.rb:381 Calling YaST client general_proposal
&lt;1&gt; linux(1966) [Ruby] yast/wfm.rb:79 Call client /usr/share/YaST2/clients/general_proposal.rb
&lt;1&gt; linux(1966) [Ruby] clients/general_proposal.rb:49 ----------------------------------------
&lt;1&gt; linux(1966) [Ruby] clients/general_proposal.rb:50 General network settings proposal started
&lt;1&gt; linux(1966) [Ruby] clients/general_proposal.rb:51 Arguments: ["AskUser", $["chosen_id":"networkmode", "has_next":false]]
&lt;1&gt; linux(1966) [Ruby] yast/ops.rb:37 Builtin index called on nil.
&lt;1&gt; linux(1966) [Ruby] yast/ops.rb:37 Builtin index called on nil.
&lt;2&gt; linux(1966) [Ruby] modules/CWM.rb:477 foreach builtin called on wrong type NilClass
&lt;1&gt; linux(1966) [Ruby] yast/ops.rb:37 Builtin index called on nil.
&lt;1&gt; linux(1966) [Ruby] yast/ops.rb:37 Builtin index called on nil.
&lt;1&gt; linux(1966) [Ruby] clients/general_proposal.rb:144 General network settings proposal finished
&lt;1&gt; linux(1966) [Ruby] clients/general_proposal.rb:145 --------------

 ![inst_ruby_m3_network_setup](https://f.cloud.github.com/assets/1658828/811085/337c8dbc-eec9-11e2-9bd4-b476172ae517.png)

**Comment by jsuchome** [comment]
Seems to by fixed by the fix of https://github.com/yast/ycp-killer/issues/504.

Not yet on media, but after installing latest ruby-bindings on installed system, it works
