### ISSUE TITLE
'Network Interfaces' not usable when started from 'Network Configuration' overview

### ISSUE THREAD

**Issue by gabi2** [yast/ycp-killer#565]
Milestone 3, don't use automatic configuration.
'Network Settings' module is not usable.
y2log:
&lt;1&gt; linux(1966) [Interpreter] clients/inst_proposal.rb:381 Called YaST client returned.
&lt;1&gt; linux(1966) [ncurses] NCPopupMenu.cc(postAgain):115 Menu item: &Network Interfaces...
&lt;1&gt; linux(1966) [Ruby] clients/inst_proposal.rb:167 Proposal - UserInput: 'lan'
&lt;1&gt; linux(1966) [Interpreter] clients/inst_proposal.rb:381 Calling YaST client lan_proposal
&lt;1&gt; linux(1966) [Ruby] yast/wfm.rb:79 Call client /usr/share/YaST2/clients/lan_proposal.rb
&lt;1&gt; linux(1966) [Ruby] clients/lan_proposal.rb:53 ----------------------------------------
&lt;1&gt; linux(1966) [Ruby] clients/lan_proposal.rb:54 Lan proposal started
&lt;1&gt; linux(1966) [Ruby] clients/lan_proposal.rb:55 Arguments: ["AskUser", $["chosen_id":"lan", "has_next":false]]
&lt;1&gt; linux(1966) [Ruby] modules/LanUdevAuto.rb:492 AY profile $["net-udev":$[], "s390-devices":$[]]
&lt;1&gt; linux(1966) [Ruby] modules/Lan.rb:862 Exported map: $["config":$["config":$["CHECK_DUPLICATE_IP":false, "CONNECTION_CHECK_BEFORE_IFDOWN":false, "CONNECTION_CLOSE_BEFORE_IFDOWN":false, "CONNECTION_SEND_KILL_SIGNAL":false, "CONNECTION_SHOW_WHEN_IFSTATUS":false, "CONNECTION_UMOUNT_NFS_BEFORE_IFDOWN":false, "DEBUG":false, "DEFAULT_BROADCAST":"+", "FIREWALL":true, "FORCE_PERSISTENT_NAMES":"", "GLOBAL_POST_UP_EXEC":true, "GLOBAL_PRE_DOWN_EXEC":true, "IFPLUGD_OPTIONS":"-f -I -b", "LINKLOCAL_INTERFACES":"eth_[0-9]|tr_[0-9]|wlan[0-9]|ath[0-9]", "LINK_READY_WAIT":0, "MANDATORY_DEVICES":"", "NETCONFIG_DNS_FORWARDER":"resolver", "NETCONFIG_DNS_FORWARDER_FALLBACK":true, "NETCONFIG_DNS_POLICY":"auto", "NETCONFIG_DNS_RANKING":"auto", "NETCONFIG_DNS_STATIC_SEARCHLIST":"", "NETCONFIG_DNS_STATIC_SERVERS":"", "NETCONFIG_MODULES_ORDER":"dns-resolver dns-bind dns-dnsmasq nis ntp-runtime", "NETCONFIG_NIS_POLICY":"auto", "NETCONFIG_NIS_SETDOMAINNAME":true, "NETCONFIG_NIS_STATIC_DOMAIN":"", "NETCONFIG_NIS_STATIC_SERVERS":"", "NETCONFIG_NTP_POLICY":"auto", "NETCONFIG_NTP_STATIC_SERVERS":"", "NM_ONLINE_TIMEOUT":"0", "NOZEROCONF":false, "SEND_GRATUITOUS_ARP":false, "USE_SYSLOG":true, "WAIT_FOR_INTERFACES":30, "WIRELESS_REGULATORY_DOMAIN":""], "dhcp":$["DHCLIENT6_BIN":"", "DHCLIENT6_RELEASE_BEFORE_QUIT":false, "DHCLIENT_BIN":"", "DHCLIENT_CLIENT_ID":"", "DHCLIENT_DEBUG":false, "DHCLIENT_HOSTNAME_OPTION":"AUTO", "DHCLIENT_PRIMARY_DEVICE":"", "DHCLIENT_RELEASE_BEFORE_QUIT":false, "DHCLIENT_SET_DEFAULT_ROUTE":true, "DHCLIENT_SET_HOSTNAME":false, "DHCLIENT_SLEEP":0, "DHCLIENT_TIMEOUT":0, "DHCLIENT_USER_OPTIONS":"", "DHCLIENT_USE_LAST_LEASE":true, "DHCLIENT_VENDOR_CLASS_ID":"", "DHCLIENT_WAIT_AT_BOOT":15, "DHCP6C_USER_OPTIONS":"", "DHCPCD_USER_OPTIONS":"", "WRITE_HOSTNAME_TO_HOSTS":false]], "devices":$["enp":$["enp0s3":$["BOOTPROTO":"dhcp", "BROADCAST":"", "ETHTOOL_OPTIONS":"", "IPADDR":"", "MTU":"", "NAME":"82540EM Gigabit Ethernet Controller", "NETMASK":"", "NETWORK":"", "REMOTE_IPADDR":"", "STARTMODE":"auto", "USERCONTROL":"no", "_aliases":$[]]], "lo":$["lo":$["BROADCAST":"127.255.255.255", "FIREWALL":"no", "IPADDR":"127.0.0.1", "NETMASK":"255.0.0.0", "NETWORK":"127.0.0.0", "PREFIXLEN":"8", "STARTMODE":"auto", "USERCONTROL":"no"]]], "dns":$["dhcp_hostname":true, "domain":"site", "hostname":"linux-sxiw", "resolv_conf_policy":"auto", "write_hostname":false], "ipv6":true, "keep_install_network":false, "managed":false, "net-udev":$[], "routing":$["ip_forward":false], "s390-devices":$[], "start_immediately":false]
&lt;1&gt; linux(1966) [ui] YPushButton.cc(setFunctionKey):188 Guessing button role YOKButton for YPushButton "Next" at 0x7f5fdc03e6b0 from function key F10
&lt;1&gt; linux(1966) [Ruby] yast/ops.rb:37 Builtin index called on nil.
&lt;1&gt; linux(1966) [Ruby] yast/ops.rb:37 Builtin index called on nil.
&lt;1&gt; linux(1966) [Ruby] yast/ops.rb:37 Builtin index called on nil.
&lt;2&gt; linux(1966) [ui-shortcuts] YShortcutManager.cc(resolveConflict):292 Couldn't resolve shortcut conflict for YDumbTab "YDumbTab [&Tab] [T&ab] [Tab]" at 0x7f5fdc03ac20 - assigning no shortcut
&lt;1&gt; linux(1966) [Ruby] yast/ops.rb:37 Builtin index called on nil.
&lt;1&gt; linux(1966) [Ruby] yast/ops.rb:44 Index 0 is out of array size
&lt;1&gt; linux(1966) [Ruby] yast/ops.rb:44 Index 1 is out of array size
&lt;1&gt; linux(1966) [Ruby] modules/NetworkInterfaces.rb:970 NetworkInterfaces::Import - done, cache content: $["enp":$["enp0s3":$["BOOTPROTO":"dhcp", "BROADCAST":"", "ETHTOOL_OPTIONS":"", "IPADDR":"", "MTU":"", "NAME":"82540EM Gigabit Ethernet Controller", "NETMASK":"", "NETWORK":"", "REMOTE_IPADDR":"", "STARTMODE":"auto", "USERCONTROL":"no", "_aliases":$[]]], "lo":$["lo":$["BROADCAST":"127.255.255.255", "FIREWALL":"no", "IPADDR":"127.0.0.1", "NETMASK":"255.0.0.0", "NETWORK":"127.0.0.0", "PREFIXLEN":"8", "STARTMODE":"auto", "USERCONTROL":"no"]]]
&lt;1&gt; linux(1966) [Ruby] modules/DNS.rb:511 DNS Import:
&lt;1&gt; linux(1966) [Ruby] modules/DNS.rb:512 nameservers=[]
&lt;1&gt; linux(1966) [Ruby] modules/DNS.rb:513 searchlist=[]
&lt;1&gt; linux(1966) [Ruby] modules/DNS.rb:514 hostname=linux-sxiw
&lt;1&gt; linux(1966) [Ruby] modules/DNS.rb:515 domain=site
&lt;1&gt; linux(1966) [Ruby] modules/DNS.rb:516 dhcp_hostname=true, write_hostname=false
&lt;1&gt; linux(1966) [Ruby] clients/lan_proposal.rb:237 Lan proposal finished
&lt;1&gt; linux(1966) [Ruby] clients/lan_proposal.rb:238 ----------------------------------------

![inst_ruby_m3_network_settings](https://f.cloud.github.com/assets/1658828/811133/cf84f75c-eeca-11e2-8cd0-c6e3f9054b4d.png)

**Comment by jsuchome** [comment]
It may be caused by similar issues in bootloader (already fixed, AFAIK).

Does it behave differently on installed system?

**Comment by dmajda** [comment]
> It may be caused by similar issues in bootloader (already fixed, AFAIK).

That's very likely. Let's wait for a new working build (hopefully today) and let's try to reproduce this bug (and other similar issues reported) there.

**Comment by jsuchome** [comment]
Yes, the fix for https://github.com/yast/ycp-killer/issues/504 helps here as well (it is not on media yet, but I installed on running system, where it is also able to reproduce the issue)
