### ISSUE TITLE
"Builtin index called on nil" not helping

### ISSUE THREAD

**Issue by jsuchome** [yast/ycp-killer#575]
Sometimes I find logs like this in y2log:

yast/ops.rb:64 Builtin index called on nil
...
yast/ops.rb:71 Index 0 is out of array size

I assume there's something wrong in the code that causes such log messages, however, I cannot know where, since it does not log specific wrong piece of code, just ops.rb and that does not help

**Comment by jreidinger** [comment]
agreed, I will fix it and place where it is called to be useful

**Comment by jreidinger** [comment]
fixed in https://github.com/yast/yast-ruby-bindings/commit/25075999dc69ba225ed67175324650084f8c6641
