### ISSUE TITLE
Ldap::file_server not known to UsersLdap.pm

### ISSUE THREAD

**Issue by jsuchome** [yast/ycp-killer#576]
UsersLdap.pm checks the variable file_server from Ldap.rb and gets

[Perl] YCP.cc(XS_YCP_call_ycp):158 No such symbol Ldap::file_server

The perl call is unchanged from previous version and worked with Ldap.ycp

**Comment by jsuchome** [comment]
The reason seems to be that when Ldap.rb variables (and i assume this happens for all other modules) exports its variables using

```
publish :variable => :use_gui, :type => "boolean"
...
publish :variable => :file_server, :type => "boolean"
```

Only some of those publish calls actually happen. With verbose logging, I can see that last published variable is :openldap_modified - see that the very next variable (base_dn) to publish is marked with :private tag. However, after set of private ones, there's still set of non-private ones, that do not get published.

Maybe addVariables function of YRubyNamespace.cc skips all remaining once it finds first public one?

**Comment by jreidinger** [comment]
fixed in https://github.com/yast/yast-ruby-bindings/commit/9b48af851b8b9fe049f541ac564d894f5f0f4376

Thanks for catch, it was stupid bug.
