### ISSUE TITLE
/usr/lib64/ruby/vendor_ruby/2.0.0/yast/yast.rb:136: warning: already initialized constant Yast::YaPI

### ISSUE THREAD

**Issue by jsuchome** [yast/ycp-killer#592]
running yast2 backup seems to be fine, but at the end I get these messages on console:

/usr/lib64/ruby/vendor_ruby/2.0.0/yast/yast.rb:136: warning: already initialized constant Yast::YaPI
/usr/lib64/ruby/vendor_ruby/2.0.0/yast/yast.rb:93: warning: previous definition of YaPI was here
given is experimental at /usr/share/YaST2/modules/YaPI/HTTPD.pm line 358 (#1)
    (S experimental::smartmatch) given depends on both a lexical $_ and
    smartmatch, both of which are experimental, so its behavior may change or
    even be removed in any future release of perl.
    See the explanation under "Experimental Details on given and when" in perlsyn.

when is experimental at /usr/share/YaST2/modules/YaPI/HTTPD.pm line 359 (#2)
    (S experimental::smartmatch) when depends on smartmatch, which is
    experimental.  Additionally, it has several special cases that may
    not be immediately obvious, and their behavior may change or
    even be removed in any future release of perl.
    See the explanation under "Experimental Details on given and when" in perlsyn.

when is experimental at /usr/share/YaST2/modules/YaPI/HTTPD.pm line 366 (#2)
given is experimental at /usr/share/YaST2/modules/YaPI/HTTPD.pm line 425 (#1)
when is experimental at /usr/share/YaST2/modules/YaPI/HTTPD.pm line 426 (#2)
when is experimental at /usr/share/YaST2/modules/YaPI/HTTPD.pm line 433 (#2)
given is experimental at /usr/share/YaST2/modules/YaPI/HTTPD.pm line 459 (#1)
when is experimental at /usr/share/YaST2/modules/YaPI/HTTPD.pm line 460 (#2)
when is experimental at /usr/share/YaST2/modules/YaPI/HTTPD.pm line 468 (#2)
given is experimental at /usr/share/YaST2/modules/YaPI/HTTPD.pm line 533 (#1)
when is experimental at /usr/share/YaST2/modules/YaPI/HTTPD.pm line 534 (#2)
when is experimental at /usr/share/YaST2/modules/YaPI/HTTPD.pm line 543 (#2)

Not sure what (if anything) is ruby related, maybe just the first messages?

**Comment by jsuchome** [comment]
This is shown in other modules using YaPI, like, just after start of 'yast2 ca_mgm' I get:

/usr/lib64/ruby/vendor_ruby/2.0.0/yast/yast.rb:136: warning: already initialized constant Yast::YaPI
/usr/lib64/ruby/vendor_ruby/2.0.0/yast/yast.rb:93: warning: previous definition of YaPI was here

**Comment by jreidinger** [comment]
yes, this part is from ruby. I will investigate it

**Comment by jreidinger** [comment]
fixed in https://github.com/yast/yast-ruby-bindings/commit/36cc74ba3c47ad4dea23272851db8666174c4eca
