### ISSUE TITLE
suspicious log errors with yast2 dirinstall

### ISSUE THREAD

**Issue by jsuchome** [yast/ycp-killer#594]

**Comment by jsuchome** [comment]
running yast2-dirinstall, I've met some red color in y2log. I do not know if it affects the functionality of the module, but it should be investigated.

See backtrace starting at 12:30:56 in http://pastebin.suse.de/7490

**Comment by jreidinger** [comment]
it is quite funny. y2log is intended to write full backtrace when given negative number, but there is bug in implementation that doesn't do it. and progress use it - https://github.com/yast/yast-yast2/blob/master/library/wizard/src/Progress.ycp#L757

see https://github.com/yast/yast-core/blob/master/libycp/src/YCPBuiltinMisc.cc#L504

so actually it is feature and not bug :smile:

**Comment by jreidinger** [comment]
so difference is that ycp prints `Progress bar has only 100 steps, not 101.` without backtrace and ruby bindings correctly attach backtrace.
