### ISSUE TITLE
sequencer handles incorrectly sequences from ycp

### ISSUE THREAD

**Issue by jsuchome** [yast/ycp-killer#598]
When I test old ycp-based module in ruby-based yast environment, the module behaves strangely - dialogs are called in wrong order. 

When everything is in ruby, it works correctly.

Example (seq.ycp) is here: http://pastebin.suse.de/7499

Try running 'yast2 ./seq.ycp' on yast-ruby system.

**Comment by jreidinger** [comment]
fixed in https://github.com/yast/yast-ruby-bindings/commit/b63ecc7f3671e61fdf47442d12514a21ce19a381
