### ISSUE TITLE
Lost files in http-server translation

### ISSUE THREAD

**Issue by jsuchome** [yast/ycp-killer#619]
See https://github.com/yast/yast-http-server/commit/67ca46cf21fc8f530250ae1880b04b3cde488250#src/include/http-server

New wizard-dialog.rb is empty, while wizard-dialog.ycp certainly wasn't

**Comment by dmajda** [comment]
There are 4 files affected in total:
- `http-server/src/include/http-server/wizard-dialog.rb`
- `http-server/src/include/http-server/dialogs.rb`
- `multipath/src/include/multipath/options.rb`
- `multipath/src/include/multipath/complex.rb`

**Comment by dmajda** [comment]
This is caused by wrongly specified `include_wrappers` in YCP Killer metadata for http-server and multipath. Patch coming soon...

**Comment by dmajda** [comment]
I fixed YCP Killer in #620, re-converted affected modules and merged results into master (https://github.com/yast/yast-http-server/pull/6, https://github.com/yast/yast-multipath/pull/2). Closing.
