### ISSUE TITLE
Problems with arg_ref

### ISSUE THREAD

**Issue by aschnell** [yast/ycp-killer#622]
We had a strange bug in yast-storage with the Ruby code for adding new LVM logical volumes (also see [bug #834330](https://bugzilla.novell.com/show_bug.cgi?id=834330)).

In ep-lvm-lib.rb the function "EpCreateLogicalVolume" has a local variable "data".  That variable is passed by reference to "DlgCreateLogicalVolume" in ep-lvm-dialogs.rb along with a reference to the function "Commit". Commit uses "data". So the code looks roughly like this:

<pre>
def EpCreateLogicalVolume(device)

  data = { ... }

  _Commit = lambda do
    do something with data
  end

  data_ref = arg_ref(data);
  DlgCreateLogicalVolume(data_ref, fun_ref(_Commit, "symbol ()"))
  data = data_ref.value;

end

def DlgCreateLogicalVolume(data, _Commit)

  modify data

  _Commit.call

end
</pre>

The problem is that "data" when used in "Commit" has wrong values; it's neither the original value set in "EpCreateLogicalVolume" nor the value set in "DlgCreateLogicalVolume" but some mixture.

It's caused by the fact that "data = data_ref.value" happens after calling "Commit".

We fixed this by passing "data" to "Commit"

**Comment by mvidner** [comment]
It would be great if you could create a self-contained YCP test case for this.

**Comment by aschnell** [comment]
Creating a test from scratch failed. Apparently the way DlgCreateLogicalVolume modifies "data" is important and also complex.

**Comment by cwh42** [comment]
In case that this problem has not already been fixed in the past we don't need to fix it now either.
