### ISSUE TITLE
 y2r crashes

### ISSUE THREAD

**Issue by varkoly** [yast/ycp-killer#624]
y2r crashes even on the simpliest ycp file:
## test.ycp:

{
    import "UI";
    import "Wizard";
    textdomain "autoinst";

```
define void go () ``{
    Wizard::CreateDialog();
}
go();
UI::CloseDialog();
```
## }

y2r -M /usr/share/YaST2/modules/ test.ycp
/usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:285:in `element_to_node': undefined method`to_sym' for nil:NilClass (NoMethodError)
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:189:in `element_to_node'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:189:in`element_to_node'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:601:in `block in extract_children'
        from /usr/lib64/ruby/gems/1.9.1/gems/nokogiri-1.5.6/lib/nokogiri/xml/node_set.rb:239:in`block in each'
        from /usr/lib64/ruby/gems/1.9.1/gems/nokogiri-1.5.6/lib/nokogiri/xml/node_set.rb:238:in `upto'
        from /usr/lib64/ruby/gems/1.9.1/gems/nokogiri-1.5.6/lib/nokogiri/xml/node_set.rb:238:in`each'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:601:in `map'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:601:in`extract_children'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:606:in `extract_collection'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:199:in`element_to_node'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:380:in `element_to_node'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:189:in`element_to_node'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:601:in `block in extract_children'
        from /usr/lib64/ruby/gems/1.9.1/gems/nokogiri-1.5.6/lib/nokogiri/xml/node_set.rb:239:in`block in each'
        from /usr/lib64/ruby/gems/1.9.1/gems/nokogiri-1.5.6/lib/nokogiri/xml/node_set.rb:238:in `upto'
        from /usr/lib64/ruby/gems/1.9.1/gems/nokogiri-1.5.6/lib/nokogiri/xml/node_set.rb:238:in`each'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:601:in `map'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:601:in`extract_children'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:606:in `extract_collection'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:199:in`element_to_node'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:189:in `element_to_node'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:136:in`xml_to_ast'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r/parser.rb:69:in `parse'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/lib/y2r.rb:10:in`compile'
        from /usr/lib64/ruby/gems/1.9.1/gems/y2r-1.0.1/bin/y2r:71:in `<top (required)>'
        from /usr/bin/y2r:23:in`load'
        from /usr/bin/y2r:23:in `<main>'
# 

The system is openSUSE 12.3 with all updates and istalled as you've described it. The only difference ist, that the mentioned repository http://download.opensuse.org/repositories/YaST:/Head:/ruby/openSUSE_12.3/
does not exists anymore.

I'll send you the acces datas to my VM.

**Comment by jreidinger** [comment]
After investigation problem is in too old yast2-core. For future reference yast2-core must be at least 3.0.1, but it in the end breaks yast on target system, so I recommend to use for translation dedicated VM.
